import Head from 'next/head'
import React from 'react'

interface Props {
  children: JSX.Element
}

export default function Layout({children}: Props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {children}
      </main>

      <footer>
      </footer>
    </div>
  )
}
